feat(workflow): add coding style check step to GitHub Actions workflow before build

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -32,9 +32,29 @@ jobs:
             exit 0
           fi
 
+  check_coding_style:
+    needs: [is_repo_a_mirror]
+    runs-on: ubuntu-latest
+    container:
+      image: ghcr.io/epitech/coding-style-checker:latest
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v4.1.1
+      - name: Check coding style runner launching
+        run: check.sh $(pwd) $(pwd)
+      - name: verify coding style
+        run: |
+          while IFS=":" read -r FILE LINE SEVERITY RULE _; do
+              echo "::error file=$FILE,line=$LINE,title=$SEVERITY coding style error::$RULE"
+          done < "$(pwd)/coding-style-reports.log"
+
+          if [ -s "$(pwd)/coding-style-reports.log" ]; then
+              exit 1
+          fi
+
   build:
     runs-on: ubuntu-latest
-    needs: is_repo_a_mirror
+    needs: [is_repo_a_mirror, check_coding_style]
     container:
       image: epitechcontent/epitest-docker:latest
       options: --privileged
@@ -68,7 +88,7 @@ jobs:
 
   discord_and_email_report:
     runs-on: ubuntu-latest
-    needs: [is_repo_a_mirror, build, deploy]
+    needs: [is_repo_a_mirror]
     if: always()
     steps:
       - name: Checkout repository
